### ISSUE TITLE
ImportError: Cannot import name 'nonrealtimetools' on armv7l, python3.4

### ISSUE THREAD

**Issue by combs** [josiah-wolf-oberholtzer/supriya#98]
Hello, 

When I try `from supriya import *` with my Python3.4, I get the following traceback:

```
chip@ngramradio:~$ python3.4
Python 3.4.2 (default, Oct  8 2014, 14:38:51) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from supriya import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chip/supriya/supriya/__init__.py", line 3, in <module>
    from supriya.tools import *
  File "/home/chip/supriya/supriya/tools/__init__.py", line 8, in <module>
    delete_systemtools=False,
  File "/usr/local/lib/python3.4/dist-packages/abjad/tools/systemtools/ImportManager.py", line 245, in import_structured_package
    ignored_names=ignored_names,
  File "/usr/local/lib/python3.4/dist-packages/abjad/tools/systemtools/ImportManager.py", line 214, in import_public_names_from_path_into_namespace
    namespace[element] = __import__(submod, fromlist=['*'])
  File "/home/chip/supriya/supriya/tools/patterntools/__init__.py", line 11, in <module>
    globals(),
  File "/usr/local/lib/python3.4/dist-packages/abjad/tools/systemtools/ImportManager.py", line 245, in import_structured_package
    ignored_names=ignored_names,
  File "/usr/local/lib/python3.4/dist-packages/abjad/tools/systemtools/ImportManager.py", line 190, in import_public_names_from_path_into_namespace
    submodule_name)
  File "/usr/local/lib/python3.4/dist-packages/abjad/tools/systemtools/ImportManager.py", line 25, in _get_public_function_names_in_module
    mod = __import__(module_file, fromlist=['*'])
  File "/home/chip/supriya/supriya/tools/patterntools/NonrealtimeEventPlayer.py", line 3, in <module>
    from supriya.tools.nonrealtimetools.SessionObject import SessionObject
  File "/home/chip/supriya/supriya/tools/nonrealtimetools/__init__.py", line 11, in <module>
    globals(),
  File "/usr/local/lib/python3.4/dist-packages/abjad/tools/systemtools/ImportManager.py", line 245, in import_structured_package
    ignored_names=ignored_names,
  File "/usr/local/lib/python3.4/dist-packages/abjad/tools/systemtools/ImportManager.py", line 190, in import_public_names_from_path_into_namespace
    submodule_name)
  File "/usr/local/lib/python3.4/dist-packages/abjad/tools/systemtools/ImportManager.py", line 25, in _get_public_function_names_in_module
    mod = __import__(module_file, fromlist=['*'])
  File "/home/chip/supriya/supriya/tools/nonrealtimetools/Bus.py", line 7, in <module>
    class Bus(SessionObject):
  File "/home/chip/supriya/supriya/tools/nonrealtimetools/Bus.py", line 130, in Bus
    def get(self, offset=None):
  File "/home/chip/supriya/supriya/tools/nonrealtimetools/SessionObject.py", line 71, in require_offset
    from supriya.tools import nonrealtimetools
ImportError: cannot import name 'nonrealtimetools'
```

Might you have any suggestions? Here is a little more about this machine:

```
chip@ngramradio:~$ uname -a
Linux ngramradio 4.4.13-ntc-mlc #1 SMP Thu Nov 3 01:28:54 UTC 2016 armv7l GNU/Linux
```

**Comment by josiah-wolf-oberholtzer** [comment]
Hey, thanks for the report. I can reproduce with Python 3.4 on my OSX machine.

I've pushed a commit to `master`. Would you mind pulling and seeing if the import works for you?

**Comment by combs** [comment]
Works a treat. Thank you!
